likelion_11th_5week_django/likelion11th/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likelion_11th_5week_django/main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second/', secondpage, name="secondpage"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
]

likelion_11th_5week_django/main/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    writer = models.CharField(max_length=100)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to="blog/", blank=True, null=True)
    
    def __str__(self):
        return self.title
    
    def summary(self):
        return self.body[:20]
    
    

likelion_11th_5week_django/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog
from django.utils import timezone

def detail(request, id):
    blog = get_object_or_404(Blog, pk = id)
    return render(request, 'main/detail.html',{'blog':blog})

def mainpage(request):
    blogs = Blog.objects.all()
    return render(request, 'main/mainpage.html', {'blogs':blogs})

def secondpage(request):
    return render(request, 'main/secondpage.html')

def create(request):
    new_blog = Blog()
    new_blog.title = request.POST['title']
    new_blog.writer = request.POST['writer']
    new_blog.pub_date = timezone.now()
    new_blog.body = request.POST['body']
    new_blog.image = request.FILES.get('image')

    new_blog.save()
    
    return redirect('main:detail', new_blog.id)

def new(request):
    return render(request, 'main/new.html')

def edit(request, id):
    edit_blog = Blog.objects.get(id=id)
    return render(request, 'main/edit.html', {'blog' : edit_blog})

def update(request, id):
    update_blog = Blog.objects.get(id=id)
    update_blog.title = request.POST['title']
    update_blog.writer = request.POST['writer']
    update_blog.pub_date = timezone.now()
    update_blog.body = request.POST['body']
    
    update_blog.save()
    return redirect('main:detail', update_blog.id)    

def delete(request, id):
    delete_blog = Blog.objects.get(id=id)
    delete_blog.delete()
    return redirect('main:mainpage')

likelion_11th_5week_django/likelion11th/templates/base.html
<!doctype html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/project.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>dgu_likelion11th</title>
</head>
<body>
    {% include 'shared/_navbar.html' %}

    {% block content %}

    {% endblock %}
</body>
</html>

likelion_11th_5week_django/likelion11th/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid" style="background-color: #e3f2fd;">
    <!-- mainpage 링크 연결 -->
    <a class="navbar-brand" href="{% url 'main:mainpage' %}">DGU_likelion_11th</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item">
            <!-- secondpage 링크 연결 -->
            <a class="nav-link active" aria-current="page" href="{% url 'main:secondpage' %}">Secondpage</a>
        </li>
        </ul>
    </div>
    </div>
</nav>

likelion_11th_5week_django/main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{blog.title}}</h1>
작성자 : {{blog.writer}}
날짜 : {{blog.pub_date}}
<hr>
{% if blog.image %}
    <p><img src="{{blog.image.url}}" alt="사진"></p>
{% endif %}
<p>{{blog.body}}</p>
<a href = "{% url 'main:edit' blog.id %}">수정하기</a>
<a href = "{% url 'main:delete' blog.id %}">삭제하기</a>
{% endblock %}

likelion_11th_5week_django/main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>글 수정하기</h1>
    <form action="{% url 'main:update' blog.id %}" method="POST">
        {%csrf_token%}
        <p>제목 : <input type="text" name="title"></p>
        <p>작성자 : <input type="text" name="writer"></p>
        <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10">{{blog.body}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</div>
{% endblock %}

likelion_11th_5week_django/main/templates/main/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Hello! _mainpage</h1>
<img src="{% static 'images/logo.png' %}" style="width:500px;">
<br>
<a href="{% url 'main:new' %}">글 쓰기</a>

<h1>글 목록</h1>

<div>
    {% for blog in blogs %}
    <div>
        <h3>{{blog.title}}</h3>
        {{blog.writer}}<br>
        {{blog.summary}}
        <a href="{%url 'main:detail' blog.id %}">...자세히</a>
        <br>
    </div>
    {% endfor %}
</div>

{% endblock %}

likelion_11th_5week_django/main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>글 작성하기</h1>
<form action="{%url 'main:create'%}" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <p>제목 : <input type="text" name="title"></p>
    <p>작성자 : <input type="text" name="writer"></p>
    <p> 사진 : <input type="file" name="image"></p>
    <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

likelion_11th_5week_django/main/templates/main/secondpage.html
{% extends 'base.html' %}
{% block content %}

{%load static%}

<h1>Hello! _secondpage</h1>
<img src="{% static 'images/logo.png' %}" style="width:500px;">

{% endblock %}